[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "selenium-proxy"
requires-python = ">=3.12"
dynamic = ["version", "dependencies"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}
