name: release
on:
  push:
    tags:
      - '*'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/le0-dot/selenium-proxy:${{ github.ref_name }}
  release:
    runs-on: ubuntu-latest
    permissions:
          contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Upload protobuf file
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: src/selenium_proxy/messages.proto
          asset_name: messages.proto
          tag: ${{ github.ref }}
